### ISSUE TITLE
works on console ?

### ISSUE THREAD

**Issue by comonier** [MrButtersDEV/SilkySpawnersLITE#4]
>silky give zombie ennoguanabara
[01:06:51] [Server thread/INFO]: Invalid target - null
[01:06:51] [Server thread/WARN]: Unexpected exception while parsing console command "silky give zombie ennoguanabara"
org.bukkit.command.CommandException: Unhandled exception executing command 'silky' in plugin SilkySpawnersLITE v1.0.15-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:3145-Spigot-9472b09-f992ce6]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:3145-Spigot-9472b09-f992ce6]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:764) ~[server.jar:3145-Spigot-9472b09-f992ce6]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:749) ~[server.jar:3145-Spigot-9472b09-f992ce6]
        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:473) ~[server.jar:3145-Spigot-9472b09-f992ce6]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:437) ~[server.jar:3145-Spigot-9472b09-f992ce6]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[server.jar:3145-Spigot-9472b09-f992ce6]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027) ~[server.jar:3145-Spigot-9472b09-f992ce6]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3145-Spigot-9472b09-f992ce6]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getName()" because "target" is null
        at us.thezircon.play.silkyspawnerslite.commands.SilkySpawner.subcommands.give.perform(give.java:115) ~[?:?]
        at us.thezircon.play.silkyspawnerslite.commands.SilkySpawner.Silky.onCommand(Silky.java:39) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:3145-Spigot-9472b09-f992ce6]
        ... 9 more

**Comment by comonier** [comment]
i tried on game and not have console problems - just on console

**Comment by comonier** [comment]
there is any permissions to not need silktouch enchant on pickaxe ?
site says "Toggleable silk touch permission" but i not find that

**Comment by comonier** [comment]
#########################################################################################
#        _____ _ _ _               _____                                                #
#       / ____(_) | |             / ____|                                     L I T E   #
#      | (___  _| | | ___   _    | (___  _ __   __ ___      ___ __   ___ _ __ ___       #
#       \___ \| | | |/ / | | |    \___ \| '_ \ / _` \ \ /\ / / '_ \ / _ \ '__/ __|      #
#       ____) | | |   <| |_| |    ____) | |_) | (_| |\ V  V /| | | |  __/ |  \__ \      #
#      |_____/|_|_|_|\_\\__, |   |_____/| .__/ \__,_| \_/\_/ |_| |_|\___|_|  |___/      #
#                        __/ |          | |                                             #
#                       |___/           |_|                                             #
#                                                                                       #
#########################################################################################
# By: BUTTERFIELD8 & The Zircon Network                                                 #
# Discord: https://discord.gg/7xfSC5p                                                   #
#########################################################################################

#Should a minded spawner drop to the ground or to the players inventory. [true=ground | false=inventory]
doDrop2Ground: false

#Anvil Rename - This will allow players to change the name of a Spawner
#Please note if 'true' players will be able to rename spawners and this can be used to scam them!
anvilRename: false

#Should players be able to mine spawners without the permission.
requireMineperm: true

#Drop Chance -> 0.00 = 0% | 1.00 = 100%
spawnerDropChance: 1.00

#Sets the cost of mining a spawner if enabled.
#PLEASE NOTE: This will require Vault to work!
chargeOnBreak:
  enabled: false
  price: 50.00
  sendMSG: true

# Blacklist worlds that you don't want player to be able to mine spawners.
# This would cause the spawner to break and drop xp for all worlds on the blacklist!
blacklist:
  - exampleworld
  
  **were is the "need silktouch enchant" true/false?**

**Comment by MrButtersDEV** [comment]
What exactly is the issue there is a lot here? The error says unknown target so check the user's name "ennoguanabara" to make sure it matches in case.  

Also, `reqireMineperm` refers to the permission nodes to restrict functionality to users. If you're requesting an option to ignore the enchant requirement, please make a new issue and make it a request.

**Comment by MrButtersDEV** [comment]
Please re-open this issue if it has not been resolved.
